### ISSUE TITLE
Can't reproduce metrics

### ISSUE THREAD

**Issue by RealAntonVoronov** [WANGXinyiLinda/concept-based-demonstration-selection#1]
Hello. Thank you for a great work and for sharing the code. I was trying to reproduce your scores on dataset 'sst2' reported in paper. I was using learned concepts from the Google Drive link (folder tune-train) and running the following script:
```
TRAIN_METHOD=direct
TEST_METHOD=direct
LR=1e-2
N_PREFIX=10
DATASET=glue-sst2
TRAIN_TASK=tune
SPLIT=train
MODEL=gpt2-large
TRAIN_SIZE=100
STEP=100000
K=4
DIFFICULTY=concept_calibrated
CUDA_VISIBLE_DEVICES=5 python test.py\
    --dataset $DATASET\
    --gpt $MODEL\
    --method $TEST_METHOD\
    --test_batch_size 16\
    --out_dir out/$MODEL\
    --k $K\
    --embedding_dir embeddings/\
    --use_demonstrations\
    --concept_temperature 50\
    --similarity_temperature 0.1\
    --train_size $TRAIN_SIZE\
    --difficulty $DIFFICULTY\
    --n_prefix_tokens $N_PREFIX\
    --concept_dir $DIFFICULTY-$K/gpt2-large/$TRAIN_TASK-$SPLIT-$TRAIN_SIZE/$DATASET-$TRAIN_METHOD-prefix=$N_PREFIX-lr=$LR-$STEP\
    --prefix_embed_file checkpoints/gpt2-large/$TRAIN_TASK-$SPLIT/prefix={$N_PREFIX}-{$TRAIN_METHOD}-lr={$LR}-initByVocab/soft_embeddings-$STEP.pt\
    --prior easiest\
    --reorder\
    # --prior most_similar\
```
I have obtained final metrics over 5 seeds as follows: `None over 1 target tasks on average: Macro-F1: 37.6 +- 5.7, Accuracy: 50.6 +- 1.0` when the reported score is 86.1 What can possibly be the reason for such a huge discrepancy?

I've checked that test_prefix.sh results in the same scores that are reported as "optimal" in your paper. So the problem is not with the learned soft-tokens I guess.

**Comment by WANGXinyiLinda** [comment]
Hi, as we've shown in our paper, the causal direction ("direct" or "channel") plays a big part in the in-context learning performance.  I see you are using "direct" instead of "channel" for sst-2 here, which is not the correct causal direction for this dataset. On the other hand, as we mentioned in our paper, the choice of the datasets trained together would also influence the final performance.  The best way to reproduce our results would be using our produced checkpoint for soft prompts at [here](https://drive.google.com/drive/folders/15UeFnuJK1akAXLHPQ0IRwnf566ApxNwT?usp=share_link) and then follow the variable definition in `variables`. In the case of sst-2, the variable definition should be:
```

TRAIN_METHOD=channel
TEST_METHOD=channel
LR=1e-2
N_PREFIX=10
DATASET=glue-sst2
TRAIN_TASK=glue
SPLIT=glue
MODEL=gpt2-large
TRAIN_SIZE=100
STEP=50000
K=4
```
You can also use the above variable definition to tune your own soft prompts.

**Comment by RealAntonVoronov** [comment]
Thank you very much, now everything is reproducible and much clearer
